Agent class:
- Initializes with working_dir (default './')
- Creates working_dir if it doesn't exist
- Dynamically requires all tool files from 'tools' directory
- Has methods:
  - initialize_chat: Sets up RubyLLM chat with tools and base instructions
  - tools: Recursively collects all tool classes that inherit from RubyLLM::Tool
  - run: Main loop for interaction with user
- Uses debugger for RubyLLM::Error
- Has rate limit handling with retry
- Issues:
  - Missing frozen string literal comment
  - Unsorted file requires
  - Unnecessary Dir.exist? check
  - Missing space in parameter default
  - Debugger entry point