Tools::Bundler module:
- Helper methods:
  - run_bundle_command: Executes bundle commands and handles output/errors
  - build_command: Constructs command string with appropriate arguments
- Tool classes (all inherit from Tool):
  - Install: Installs dependencies from Gemfile (params: path, without, jobs)
  - Update: Updates specified gems (params: gems, group, source)
  - Add: Adds gem to Gemfile (params: gem_name, version, group)
  - Remove: Removes gem from Gemfile (params: gem_name)
  - List: Lists all gems (params: name for filtering)
  - Info: Shows info for specific gem (params: gem_name)
  - Outdated: Shows outdated gems (params: filter)